"""add rt_checked_at to movies

Revision ID: d2a5bea72e77
Revises: 3d29ab446561
Create Date: 2026-07-05 18:36:09.948830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a5bea72e77'
down_revision: Union[str, None] = '3d29ab446561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rt_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'rt_checked_at')
    # ### end Alembic commands ###
